### ISSUE TITLE
[BUG] Scaling wrong at 1366*788 on my win 10

### ISSUE THREAD

**Issue by bassanou** [TurtleNetwork/TurtleNetworkGUI#130] opened 2020-03-31 17:37 UTC
**Describe the bug**
Small order book on my win 10 PC

**To Reproduce**
using a PC under win 10 with 1366*788 resolusion display.

**Expected behavior**
i would like to see a bigger order book or kinda adjusted-sise sollution.

**Screenshots**

![Annotation 2020-03-31 185000](https://user-images.githubusercontent.com/62956112/78057139-8ad13600-7386-11ea-84c3-dc8d146c4572.png)

**Desktop :**

 - OS: win 10
 - Browser/JVM chrome
 - Version [80.0.3987.149]

**Additional context**

none

i love TN. good luck. /WeAreTN

**Comment by fyrak1s** [comment] 2020-04-25 03:08
Does it help if you down scale the page?

For example with CTRL+(-) in your browser?

**Comment by BlackTurtle123** [comment] 2020-05-11 13:11
@dev-campos  We do have now a scrollbar in a scrollbar.
Can we fixate that the buy and sell bars are always on the bottom off the screen? and so the second scroll bar shouldn't be needed

**Comment by BlackTurtle123** [comment] 2020-05-11 13:12
![image](https://user-images.githubusercontent.com/16037736/81565521-c1dd3300-9399-11ea-9b37-a2e4bd0a53ee.png)

**Comment by dev-campos** [comment] 2020-05-11 14:57
The outside scrollbar is caused by the beta banner, the code is built to only have the inner one. This happens on the live version too, if the screen gets too short the inner bar appears.

The correct way to fix this would be to change the banner, or if you plan to remove it after the beta period you can leave it as is rn, and when you remove it the problem will go away too.

**Comment by BlackTurtle123** [comment] 2020-05-11 15:01
> The outside scrollbar is caused by the beta banner, the code is built to only have the inner one. This happens on the live version too, if the screen gets too short the inner bar appears.
> 
> The correct way to fix this would be to change the banner, or if you plan to remove it after the beta period you can leave it as is rn, and when you remove it the problem will go away too.

Okay if you are sure about this, then this is indeed a non issue. we will remove if after beta

**Comment by dev-campos** [comment] 2020-05-11 15:06
I'll test this today to make sure, but from what I looked in the code this seems to be the issue

**Comment by dev-campos** [comment] 2020-05-11 15:23
I checked it, and removing the banner also removes the outside scrollbar

**Comment by BlackTurtle123** [comment] 2020-05-18 11:05
Okay, so closing it then

**Closed as completed by BlackTurtle123** 2020-05-18 11:05 UTC
Labels: bug, help wanted
