### ISSUE TITLE
[FEATURE] - Exchange default to TN pairs

### ISSUE THREAD

**Issue by gord0b** [TurtleNetwork/TurtleNetworkGUI#28] opened 2020-02-25 12:25 UTC
Exchange view currently defaults to show 'ALL' pairs and will potentially slow load times of page.

Suggest to default the Exchange view to 'TN' pairs.

**Comment by BlackTurtle123** [comment] 2020-02-25 12:28
I am pro this.

**Comment by BlackTurtle123** [comment] 2020-03-06 19:39
Duplicate of #29 
It's solved by doing 29

**Closed as completed** 2020-03-06 19:38 UTC
